### PR TITLE
fix #14 by extending OpenSeadragon.TileSource in a different way

### LINKED ISSUE #14: Uncaught ReferenceError: OpenSeadragon is not defined
When creating a basic application using the npm package version of GeoTIFFTileSource `2.0.1` and OpenSeadragon `4.1.1`, the webpage fails to load OpenSeadragon, stating that it is undefined.

```
Uncaught ReferenceError: OpenSeadragon is not defined
```

I followed the instructions provided, using the example code:

```
import OpenSeadragon from 'openseadragon';
import { enableGeoTIFFTileSource } from "geotiff-tilesource";

enableGeoTIFFTileSource(OpenSeadragon);
```

Disabling the `geotiff-tilesource` import results in a working OpenSeadragon viewer so there is something wrong with the wrapper code causing the module to become invalid.

Please let me know if there is something that I'm doing incorrectly, or if there is indeed something wrong with the package itself/versions of the packages.

### PR DESCRIPTION
**Pull request by pearcetm**
This patch should fix #14 by extending `OpenSeadragon.TileSource` in a different way during the build step.

Note that this means that `import { GeoTIFFTileSource } from 'src/GeoTIFFTIleSource.js'` and using the class directly to instantiate a tile source probably won't work anymore.

Bumps version to 2.0.2

### CODE REVIEW

**Comment by pearcetm** [comment]
@abiswas97 @mdushkoff This appears to fix the problem when I'm running it locally. Would you be able to build from this branch and see if it also fixes it for you? If so, I can create a new release with this patch.

**Comment by mdushkoff** [comment]
I've just built it from the `fix-14` branch and that seems like it works so far.  Thanks so much for getting to this so quickly!

**Comment by mdushkoff** [comment]
On further testing I've come across some issues.  As you mention above, the `GeoTIFFTileSource` method might be broken.  I've observed when doing:

```js
const tiffTileSources = await OpenSeadragon.GeoTIFFTileSource.getAllTileSources('source', {
  logLatency: false,
});
```

that I get yet another `Uncaught ReferenceError: OpenSeadragon is not defined`.  This points to [src/GeoTIFFTileSource.js#177](https://github.com/pearcetm/GeoTIFFTileSource/blob/fix-14/src/GeoTIFFTileSource.js#L177) where it has an undefined reference to `OpenSeadragon`.

**Comment by abiswas97** [comment]
I think I see the issue - before restructuring, the class definition of GeoTIFFTileSource was inside the enableGeoTIFFTileSource function, and inherited OpenSeadragon from the function param. I had moved the class outside to allow for exporting it on it's own, and this brought in the invalid reference. 

@mdushkoff 's solution would have worked, but the qptiff integration would break since it self calls GeoTIFFTileSource. @pearcetm I can take a closer look at this and create a fix later today

**Comment by pearcetm** [comment]
@abiswas97 Can you explain more about how this would break qptiff integration, and have you tested that? Because if you use it after instantiating it normally everything should work the same as before. It only wouldn't work for use-cases that don't use the files from `/dist`. Within the build library it should be totally fine to import the `GeoTIFFTileSource` module directly.

**Comment by pearcetm** [comment]
I just pushed some changes that I think may address this. Can you test further?

**Comment by abiswas97** [comment]
@pearcetm No I was likely wrong on the qptiff - taking a look at the changes in this PR now

**Comment by abiswas97** [comment]
I'm coming across a different error - 
```
TypeError: Cannot read properties of undefined (reading 'ready')
    at P.getHandler (openseadragon.js?v=5801959f:1784:35)
    at P.raiseEvent (openseadragon.js?v=5801959f:1807:30)
    at P.setupComplete (GeoTIFFTileSource.js:272:10)
    at P.setupLevels (GeoTIFFTileSource.js:367:10)
    at new P (GeoTIFFTileSource.js:66:12)
    at GeoTIFFTileSource.js:177:22
    at Array.map (<anonymous>)
    at GeoTIFFTileSource.js:147:26
    at async prepareGeoTIFFTileSource (tileSource.ts:48:27)
    at async initializeViewer (tileSource.ts:110:30)
```
@pearcetm are you running into this too?

**Comment by abiswas97** [comment]
@pearcetm Would you be okay with not exporting the class as is? Since a lot of its internals work by updating `OpenSeadragon.TileSource`, and users who import the class would need to perform the same steps that the enableGeoTIFFTileSource function does

**Comment by pearcetm** [comment]
> @pearcetm are you running into this too?

I don't do much with React, so my current test suite for npm module is pretty limited. This makes it tough to fully test and reproduce issues on my end... would there be a way to put a test suite together that can be easily run via npm or other tool in order to test these things?

**Comment by pearcetm** [comment]
> Would you be okay with not exporting the class as is? Since a lot of its internals work by updating OpenSeadragon.TileSource, and users who import the class would need to perform the same steps that the enableGeoTIFFTileSource function does

If someone were to `import { GeoTIFFTileSource } from './main.js'` would it work right? (Not via npm but as a plain javascript module.) My understanding is that `main.js` takes care of adding GeoTIFFTileSource to OpenSeadragon and, as of the current PR, as part of that process it also adds a reference to OpenSeadragon that the GeoTIFFTileSource can use.

So, for users who want to use the package through npm they'd need to just use the `enableGeoTIFFTileSource` function, while plain scripts/modules could use the class directly.

Again though, I don't have a good way to test this fully right now so I could be wrong.

**Comment by abiswas97** [comment]
From what I tested, adding the entire class defintion back into the `enableGeoTIFFTileSource` function gets it to work. I find this a bit easier to wrap my head around, since I haven't worked with object prototypes much. Though it definitely could be cleaner.

For the import experience, the intended approach is - 
1. UMD - Add the script, script will handle the attachment by calling enableGeoTIFFTileSource. So when using UMD, no import is needed, and users don't need to directly access GeoTIFFTileSource to set it up. The setup steps are just to include `geotiff-tilesource.mjs` after `openseadragon.js`. The IIFE-like block in main.js will attach the plugin to OSD. If they ever need to access it, they can access it through `OpenSeadragon.GeoTIFFTileSource` at any point in a custom script. I guess this worked in testing since OpenSeadragon already exists in global scope when using the UMD approach. 
2. ESM - Explicitly import enableGeoTIFFTileSource, and pass the OpenSeadragon instance to it.

**Comment by pearcetm** [comment]
> So, for users who want to use the package through npm they'd need to just use the `enableGeoTIFFTileSource` function, while plain scripts/modules could use the class directly.

I suppose they may as well just access the class through the binding to OpenSeadragon. So yes, I guess it this is fine to not export the class directly.

**Comment by abiswas97** [comment]
@pearcetm in that case, I'll open a new PR that just moves the class definition into the main exported function

**Comment by pearcetm** [comment]
> @pearcetm in that case, I'll open a new PR that just moves the class definition into the main exported function

Ok, sounds good. Please bump the version to 2.0.2 and update the build as part of the PR, so I can make a new release with it.

**Comment by pearcetm** [comment]
Closing this, preempted by https://github.com/pearcetm/GeoTIFFTileSource/pull/16

**Pull request closed without merging**
